### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xxzefgh** [thisdotvoid/adonisjs-types#1]
- [x] Config | Adonis/Src/Config
- [ ] Database | Adonis/Src/Database
- [x] Env | Adonis/Src/Env
- [x] Event | Adonis/Src/Event
- [x] Encryption | Adonis/Src/Encryption
- [x] Exception | Adonis/Src/Exception
- [ ] Factory | Adonis/Src/Factory
- [x] Hash | Adonis/Src/Hash
- [x] Helpers | Adonis/Src/Helpers
- [x] Logger | Adonis/Src/Logger
- [ ] Lucid | Adonis/Src/Lucid
- [x] Adonis/Src/Request
- [x] Adonis/Src/Response
- [x] Route | Adonis/Src/Route
- [ ] Schema | Adonis/Src/Schema
- [ ] Adonis/Src/Session
- [x] View | Adonis/Src/View
- [ ] Ws | Adonis/Addons/Ws
